# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

class TestLogin():
  def setup_method(self, method):
    # self.driver = webdriver.Chrome(service=Service('C:\\Formation\\WebDriver\\chromedriver.exe'))
    self.driver = webdriver.Chrome(service=Service(ChromeDriverManager(version='107.0.5304.62').install()))

    self.driver.implicitly_wait(30)
    self.wait = WebDriverWait(self.driver, 10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.close()
    self.driver.quit()
    pass
  
  def test_login(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    self.driver.find_element(By.NAME,"username").clear()
    self.driver.find_element(By.NAME, "username").send_keys("Admin")
    self.driver.find_element(By.NAME, "password").clear()
    self.driver.find_element(By.NAME, "password").send_keys("admin123")
    btn = self.driver.find_element(By.CSS_SELECTOR, ".oxd-button")
    # if self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".oxd-button"))) :
    #   btn.click()
    assert self.driver.find_element(By.LINK_TEXT,"Leave"),"element Leave not fund"
    assert self.driver.find_element(By.LINK_TEXT,"My Info"),"element My Info not fund"
    
  
    # self.driver.find_element(By.CSS_SELECTOR, ".oxd-userdropdown-name").click()
    # self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
# pytest test_login.py --html=test_login.html